### ISSUE TITLE
Getting error 500: error: missing clientid.

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-content-proxy#349] opened 2021-03-29 08:18 UTC
Another #337 fallout:

```json
{
  "request": {
    "id": "a750d59c-a45e-6c4d-838f-eac9b10df5dc",
    "method": "GET",
    "protocol": "HTTP/1.1",
    "h2": false,
    "is_ipv6": false,
    "url": "/helix-services/content-proxy@v2?ref=master&path=/br/query-index.json&owner=adobe&repo=theblog&root=&limit=256&offset=0",
    "referer": "https://theblog--adobe.hlx.page/br/",
    "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36",
    "accept_content": "*/*",
    "accept_language": "en-US,en;q=0.9",
    "accept_encoding": "",
    "accept_charset": "",
    "xfh": "theblog--adobe.hlx.page, helix-pages.anywhere.run",
    "via": "",
    "cache_control": "",
    "header_size": 1973,
    "body_size": 0,
    "restarts": 1,
    "versionlock": ""
  },
  "edge": {
    "cache_status": "MISS",
    "datacenter": "LON",
    "ip": "199.232.58.217"
  },
  "response": {
    "status": 500,
    "error": "Error: Missing clientId.",
    "content_type": "text/plain",
    "header_size": 879,
    "body_size": 0
  },
  "origin": {
    "host": "helix-pages.anywhere.run",
    "url": "/helix-services/content-proxy@v2?ref=master&path=/br/query-index.json&owner=adobe&repo=theblog&root=&limit=256&offset=0"
  },
  "ow": {
    "environment": "AmazonWebServices",
    "actionName": "helix-services/content-proxy@v2",
    "activationId": "c7klFhhUIAMEMHg=",
    "transactionId": ""
  },
  "client": {
    "name": "fastly",
    "number": 54113,
    "location_geopoint": {
      "lat": 51.51,
      "lon": -0.08
    },
    "city_name": "london",
    "country_name": "united kingdom",
    "connection_speed": "broadband",
    "ip": "3.9.92.122"
  },
  "time": {
    "start": "2021-03-29T03:48:47.789+0000",
    "start_msec": 1616989727789,
    "end": "2021-03-29T03:48:48.823+0000",
    "end_msec": 1616989728823,
    "elapsed": 1034198
  }
}
```

**Comment by tripodsan** [comment] 2021-03-29 08:49
> Another #377 fallout:

was is 377 ?

**Comment by trieloff** [comment] 2021-03-29 10:59
It's like #337, but for people who can't type.

**Comment by tripodsan** [comment] 2021-04-13 03:07
no reproducable....

**Comment by trieloff** [comment] 2021-04-14 09:03
Just happened again https://cq-dev.slack.com/archives/CGG9B79BK/p1618390912107000

**Comment by trieloff** [comment] 2021-04-14 09:10
```json
{
  "request": {
    "id": "3427239f-e95f-6847-8c9e-2eb9515c3b4e",
    "method": "GET",
    "protocol": "HTTP/1.1",
    "h2": false,
    "is_ipv6": false,
    "url": "/helix-services/content-proxy@v2?ref=abranch&path=/spreadsheet.json&owner=adobe&repo=helix-pages-test-content&root=&",
    "referer": "",
    "user_agent": "node-superagent/3.8.3",
    "accept_content": "",
    "accept_language": "",
    "accept_encoding": "",
    "accept_charset": "",
    "xfh": "abranch--helix-pages-test-content--adobe.hlx-3.page, helix-pages.anywhere.run",
    "via": "",
    "cache_control": "",
    "header_size": 1369,
    "body_size": 0,
    "restarts": 1,
    "versionlock": ""
  },
  "edge": {
    "cache_status": "MISS",
    "datacenter": "DCA",
    "ip": "151.101.202.122"
  },
  "response": {
    "status": 500,
    "error": "Error: Missing clientId.",
    "content_type": "text/plain",
    "header_size": 879,
    "body_size": 0
  },
  "origin": {
    "host": "helix-pages.anywhere.run",
    "url": "/helix-services/content-proxy@v2?ref=abranch&path=/spreadsheet.json&owner=adobe&repo=helix-pages-test-content&root=&"
  },
  "ow": {
    "environment": "AmazonWebServices",
    "actionName": "helix-services/content-proxy@v2",
    "activationId": "dxBaujSFIAMEMlw=",
    "transactionId": ""
  },
  "client": {
    "name": "fastly",
    "number": 54113,
    "location_geopoint": {
      "lat": 39.03,
      "lon": -77.49
    },
    "city_name": "ashburn",
    "country_name": "united states",
    "connection_speed": "broadband",
    "ip": "54.172.14.209"
  },
  "time": {
    "start": "2021-04-14T09:01:43.573+0000",
    "start_msec": 1618390903573,
    "end": "2021-04-14T09:01:43.974+0000",
    "end_msec": 1618390903974,
    "elapsed": 400568
  }
}

```

**Comment by trieloff** [comment] 2021-04-14 09:17
The `user-agent` is odd. The repository seems to be nonexisting or private.

**Comment by tripodsan** [comment] 2021-04-14 09:53
this is from one of the pages integration test, I think ( @kptdobe right? )

**Comment by kptdobe** [comment] 2021-04-14 10:10
Looks like this one: https://app.circleci.com/pipelines/github/adobe/helix-pages/4398/workflows/ca4cb2c2-4673-4366-a1e9-f3c6949ccda5/jobs/20241

**Comment by kptdobe** [comment] 2021-04-14 10:15
Corresponding source is here: https://github.com/adobe/helix-pages/blob/master/test/smoke/test-content.smoke.js
User Agent is given by `chai.request`.

**Comment by kptdobe** [comment] 2021-04-14 10:21
And finally... the repo is here: https://github.com/adobe/helix-pages-test-content (different test content combo)

**Comment by tripodsan** [comment] 2021-04-15 07:17
found the underlying problem:

```
2021-04-14T09:01:36.298Z	7a3a96f0-350b-435a-8f04-5923ebfe4972	ERROR	unable to get parameters ThrottlingException: Rate exceeded
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ThrottlingException',
  time: 2021-04-14T09:01:36.297Z,
  requestId: '0014473a-2458-445e-a5f7-3ddca2dff603',
  statusCode: 400,
  retryable: true
}

```

**Comment by tripodsan** [comment] 2021-04-15 07:20
https://github.com/adobe/helix-universal/issues/5

**Comment by tripodsan** [comment] 2021-04-15 09:10
closing as it isn't directly a problem of content-proxy. see adobe/helix-universal#5

**Closed** 2021-04-15 09:10 UTC
Labels: bug
